#!/bin/zsh

chosen=$(echo "Power Off\nReboot\nLog Out" | \
    rofi \
    -dmenu \
    -i \
    -yoffset -150 \
    -p "⏻ " \
    -theme-str 'inputbar {enabled: false;} window {width: 15%; location: center;} listview {lines: 3;}' )

case $chosen in
    "Log Out")
        herbstclient quit
        ;;
    "Reboot")
        systemctl reboot
        ;;
    "Power Off")
        systemctl poweroff
        ;;
esac

