[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#555753"
blue = "#739fcf"
cyan = "#3bf4f7"
green = "#96f73b"
magenta = "#ad7fa8"
red = "#ff0000"
white = "#eeeeec"
yellow = "#ffe880"

[colors.normal]
black = "#000000"
blue = "#3d77c2"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#9d6298"
red = "#cc0000"
white = "#d3d7cf"
yellow = "#c4a000"

[colors.primary]
background = "#030303"
foreground = "#cfcfcf"

[font]
size = 12.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrains Mono Light"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 4
